# Lecture 7 - NumPy Revision and Practice

Second assignment will be posted today evening.

We have looked at numpy already, but its worth going through it again and learning some more advanced features because no matter what scientific application you end up using python for you will use numpy heavily.


There will be many short exercises throughout this lecture, and you will spend 1-2 minutes on each before I discuss the solution with the whole class. This kind of practice is the best way to become completely familiar with operating with numpy arrays.

So please download this notebook to follow along.

In [1]:
import numpy as np

## Numpy

Main object type is `np.array`

Many ways to create it,

One way is to convert a python list

In [ ]:
python_list = [ 1,2,3 ]
np.array(python_list)

In [ ]:
arr = np.array([1,2,3])
arr

Many times a list comprehension is used to create a list and then converted to a array

In [ ]:
arr = np.array([ 2**i for i in range(10) ])
arr

In [ ]:
arr = np.array([ 2**i for i in range(10) if i!= 5 ])
arr

### Exercise
Create a numpy array that contain  intergers i  such that  0<i<100 and $2^i$ has the last digit 6

In [ ]:
#EX


Create a 2D numpy array $A$ such that $A_{ij} = i\times j$

In [ ]:
#EX


Another way to create a numpy array is with initializing functions

- np.zeros
- np.ones
- np.arange

These functions along with `reshape` can be used to create initial matrix without any for loops

In [ ]:
np.zeros((10,10))

In [ ]:
np.ones((10,10))

In [ ]:
np.arange(10)

You can combine these functions with arithmatic operations

In [ ]:
np.zeros((10,10)) + 5

In [ ]:
np.ones((10,10))*5

In [ ]:
np.arange(10)*np.ones((10,10))

In [ ]:
np.arange(10).reshape(-1,1)*np.ones((10,10))

### Exercise
Create an array of first 10 powers of 2

In [ ]:
#EX


Again, create a 2D numpy array $A$ such that $A_{ij} = i\times j$, but without using list comprehensions

In [ ]:
#EX


## Array Broadcasting

Normally you only do arithmatic operations between arrays of the same dimension

In [ ]:
np.ones((5,5,5)) 

In [ ]:
np.ones((5,5,5)) + np.arange(5*5*5).reshape(5,5,5)

In [ ]:
np.ones((5,5,5)) + np.arange(5).reshape(5,1,1)

In [ ]:
np.ones((1,5,5)) + np.ones((5,1,5))

![](http://scipy-lectures.org/_images/numpy_broadcasting.png)

### Exercise
Use array broadcasting to create a (10,10) numpy array with values
$$ A_{ij} = 2^i + j $$

In [ ]:
#EX


## Matrix creation

There are some functions to create standard matrices

In [ ]:
np.eye(10)

In [ ]:
M = np.diag(np.arange(10))
M

In [ ]:
np.diag(M)

In [ ]:
A = np.arange(15).reshape(5,3).T
A

In [ ]:
x = np.arange(5)
np.dot(A,x)

In [ ]:
A.dot(x)

### Exercise

Create this matrix 
```
array([[5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 4., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 5.]])```

In [ ]:
#EX


## Array Indexing and Slicing

In [ ]:
arr = np.arange(10)

In [ ]:
arr[5], arr[-2]

In [ ]:
arr[3:7]

In [ ]:
arr[:-2]

In [ ]:
arr[0:5:2]

In [ ]:
arr[5:0:-2]

In [ ]:
arr[::3]

Can use all the above slicing methods for each dimension of a multidemnsional array
![](http://scipy-lectures.org/_images/numpy_indexing.png)

### Exercise
Create the following matrix
```
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])```

In [ ]:
#EX


Create the following matrix
```
array([[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1.,  0.,  1.,  2.,  3.,  4., -1., -1., -1., -1.],
       [-1.,  5.,  6.,  7.,  8.,  9., -1., -1., -1., -1.],
       [-1., 10., 11., 12., 13., 14., -1., -1., -1., -1.],
       [-1., 15., 16., 17., 18., 19., -1., -1., -1., -1.],
       [-1., 20., 21., 22., 23., 24., -1., -1., -1., -1.],
       [-1., 25., 26., 27., 28., 29., -1., -1., -1., -1.],
       [-1., 30., 31., 32., 33., 34., -1., -1., -1., -1.],
       [-1., 35., 36., 37., 38., 39., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.]])```

In [ ]:
#EX


# Fancy Array Indexing

We can use numpy arrays as an index for other numpy arrays

In [ ]:
arr = np.arange(10)
arr

In [ ]:
idx = np.array([7,-5,2])

In [ ]:
arr[idx]=-1
arr

In [ ]:
arr<0

In [ ]:
arr[arr<0] = 0
arr

For multidimensional array, array indexing works different from slicing

In [ ]:
X = np.zeros((10,10))
X[3:8,3:8]=1
X

In [ ]:
X = np.zeros((10,10))
X[np.arange(3,8),np.arange(3,8)]=1
X

![](http://scipy-lectures.org/_images/numpy_fancy_indexing.png)

### Exercise
Create the following matrix
```
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])```

In [ ]:
#EX


We can use `np.where`, to get indices of the `True` values in a boolean array

In [ ]:
np.where(X>0)

## Reduction operations

Many reduction functions are available

- np.sum, np.prod
- np.min, np.max
- np.any, np.all

Partial reductions

- np.cumsum, np.cumprod

In [ ]:
X = np.arange(100).reshape(10,10)
X

In [ ]:
np.sum(X),np.prod(X)

In [ ]:
np.sum(X,axis=1)

In [ ]:
np.min(X),np.max(X)

In [ ]:
np.min(X,axis=0)

In [ ]:
Y = X>-1
Y

In [ ]:
np.all(Y)

All the above functions can be called on the array object directly

In [ ]:
X.sum(axis=0)

In [ ]:
(np.sqrt(X*X*X)<500).all()

Cumulative operations don't change the shape of the array

In [ ]:
np.cumsum(X,axis=0)

### Exercise

- Find the column with maximum column sum
- For which rows of the matrix, the sum of the first three elements of the row is greater than the sum of the last two elements of the row

In [ ]:
np.random.seed(10)
X = np.random.rand(5,5)
X

In [ ]:
#EX


In [ ]:
#EX


### Exercise
Compute the the moving average of the array `y` created below, with window size 5.

In [ ]:
np.random.seed(10)
y = np.cumsum(np.random.rand(100)-0.5)
import matplotlib.pyplot as plt
plt.plot(y);

In [ ]:
#EX


## Final Exercise

Implement the [Conway's game of Life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life) using numpy

In [ ]:
X = (np.random.rand(100,100)>0.9).astype(int)

In [ ]:
#EX
