# CME193 - Homework 2 Solution

In this assignment, you'll be analyzing an interesting dataset: the passengers of the ship *Titanic*. As you are probably familiar, the *Titanic* was a ship that collided with an iceberg on April 15, 1912 and sank. About one-third of the passengers survived. We are interested in analyzing what factors are correlated with whether a person survived (whether the person was traveling with family, the person's sex, the person's age, etc.).

## Question 1: Loading the dataset    

The dataset contains the following columns:
- `Survived`: `1` if the person survived, `0` if not
- `Pclass`: the ticket class the person was travelling under, `1` for 1st class, `2` for 2nd class, `3` for 3rd class
- `Name`: name
- `Sex`: sex, `male` for male, `female` for female
- `Age`: age
- `Siblings/Spouses Aboard`: the number of siblings and spouses aboard
- `Parents/Children Aboard`: the number of parents and children aboard
- `Fare`: the amount paid for the ticket, in pounds

Eventually, we would like to use a classification algorithm to predict the `Survived` column from the other columns (besides `Name`). This means we need to convert the non-numeric columns into numeric columns (or boolean columns, for which `True` and `False` can be interpreted as `1` and `0` respectively).

You can find the dataset at the following URL (from CS 109, originally from Kaggle):

    http://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv

Load this CSV file into a Pandas dataframe and look at the data. Convert `Pclass` and `Sex` into boolean columns; that is, create four new boolean columns, `Female`, `1st Class`, `2nd Class`, and `3rd Class`, with the appropriate values. For example, `Female` would be `True` if the person is female, `False` if the person is male.



In [1]:
import pandas as pd
df = pd.read_csv('http://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv')
df['Female'] = df['Sex'] == 'female'
df['1st Class'] = df['Pclass'] == 1
df['2nd Class'] = df['Pclass'] == 2
df['3rd Class'] = df['Pclass'] == 3
df

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
5           0       3                                    Mr. James Moran   
6           0       1                             Mr. Timothy J McCarthy   
7           0       3                      Master. Gosta Leonard Palsson   
8           1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson   
9           1       2                 Mrs. Nicholas (Adele Achem) Nasser   
10          1       3                     Miss. Marguerite Rut Sandstrom   
11          1       1                            Miss. Elizabeth Bonnell   
12          0       3                      Mr. William Henry Saundercock   
13          0       3                         Mr. Anders Johan Andersson   
14          0       3                Miss. Hulda Amanda Adolfina Vestrom   
15          1       2                     Mrs. (Mary D Kingcome) Hewlett   
16          0       3                                Master. Eugene Rice   
17          1       2                        Mr. Charles Eugene Williams   
18          0       3  Mrs. Julius (Emelia Maria Vandemoortele) Vande...   
19          1       3                             Mrs. Fatima Masselmani   
20          0       2                                Mr. Joseph J Fynney   
21          1       2                               Mr. Lawrence Beesley   
22          1       3                                 Miss. Anna McGowan   
23          1       1                        Mr. William Thompson Sloper   
24          0       3                       Miss. Torborg Danira Palsson   
25          1       3  Mrs. Carl Oscar (Selma Augusta Emilia Johansso...   
26          0       3                             Mr. Farred Chehab Emir   
27          0       1                      Mr. Charles Alexander Fortune   
28          1       3                                Miss. Ellen O'Dwyer   
29          0       3                                 Mr. Lalio Todoroff   
..        ...     ...                                                ...   
857         0       2                         Mr. Frederick Edward Giles   
858         1       1  Mrs. Frederick Joel (Margaret Welles Barron) S...   
859         0       3                           Miss. Dorothy Edith Sage   
860         0       2                              Mr. John William Gill   
861         1       2                            Mrs. (Karolina) Bystrom   
862         1       2                        Miss. Asuncion Duran y More   
863         0       1                Mr. Washington Augustus II Roebling   
864         0       3                         Mr. Philemon van Melkebeke   
865         1       3                     Master. Harold Theodor Johnson   
866         0       3                                   Mr. Cerin Balkic   
867         1       1    Mrs. Richard Leonard (Sallie Monypeny) Beckwith   
868         0       1                            Mr. Frans Olof Carlsson   
869         0       3                         Mr. Victor Vander Cruyssen   
870         1       2               Mrs. Samuel (Hannah Wizosky) Abelson   
871         1       3                           Miss. Adele Kiamie Najib   
872         0       3                       Mr. Alfred Ossian Gustafsson   
873         0       3                                Mr. Nedelio Petroff   
874         0       3                                  Mr. Kristo Laleff   
875         1       1       Mrs. Thomas Jr (Lily Alexenia Wilson) Potter   
876         1       2        Mrs. William (Imanita Parrish Hall) Shelley   
877         0       3                                

## Question 2: Building the dataset
Next, let's convert our dataset into NumPy arrays. Create a NumPy array `X` derived from the Pandas dataframe with the numerical and boolean columns, that is: `['Age', 'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Fare', 'Female', '1st Class', '2nd Class', '3rd Class']`. Create a NumPy vector `y` derived from the `Survived` column. Ensure that the entries of both `X` and `y` are floating point numbers. (Hint: if `a` is a NumPy array, then `a.astype(float)` converts the entries to floats.)

In [2]:
X = df.drop(['Survived', 'Pclass', 'Name', 'Sex'], axis=1).to_numpy().astype(float)
y = df['Survived'].to_numpy().astype(float)

# Note: df[['Survived']] would produce a NumPy matrix rather than a vector.

## Question 3: Logistic regression
Logistic regression is a classification algorithm that comes with scikit-learn. In this case, we would like to predict one of two classes, `1` if the person survived, `0` if the person did not. Normally, we would split our dataset into a training set and a test set, but for simplicity we will not do that here; instead we will train on our entire dataset.

Using scikit-learn, fit a logistic regression model to the dataset we created in Question 2. What percentage of the passengers' outcomes does the model correctly predict? What does the model think about the fate of a 30-year-old male travelling alone who paid 50 pounds for his 2nd-class ticket?

In [3]:
import numpy as np
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X, y)

/home/casey/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [4]:
np.mean(model.predict(X) == y)

# The accuracy is roughly 80%.

0.8015783540022547

In [5]:
model.predict(np.array([[30, 0, 0, 50, 0, 0, 1, 0]]))

# The person isn't predicted to survive.

array([0.])

## Question 4: Defining the model
As an exercise, we will now do logistic regression again, but this time "manually" -- without the use of scikit-learn -- by solving the underlying optimization problem. To do so, we'll make use of SciPy's `special` and `optimize` packages.

Consider a single observation $x$ (a single passenger), represented by a vector of length $k$. Logistic regression defines a model with two parameters, $\alpha$ and $\beta$, where $\alpha$ is a number and $\beta$ is a vector of length $k$. Assuming we know $\alpha$ and $\beta$, the probability that $x$ survives is the number
$$ \text{probability that }x\text{ survives} = \frac{1}{1 + \exp(-(\alpha + x^T \beta)) }.$$
Our eventual goal is to find the values for $\alpha$ and $\beta$ that results in a probability that best matches the observed outcome for $x$.

Define a function `probability_of_surviving(alpha, beta, X)` that computes probabilities of the passengers in `X` surviving,
$$ \frac{1}{1 + \exp(-(\alpha + X \beta )) },$$
where:
- `alpha` is a number $\alpha$
- `beta` is a vector $\beta$ of length $k$
- `X` is an $n$-by-$k$ matrix $X$, where each of the $n$ rows corresponds to an observation (a passenger), and each column corresponds to a feature.

This function should output a vector of length $n$, with each entry being the probability that each person survives, assuming we know $\alpha$ and $\beta$. Note that $X\beta$ should be interpreted as matrix multiplication, but all other operations (addition, exponential, division) operate elementwise. (Hint: check out SciPy's `special.expit`.)

In [6]:
import scipy.special as special

def probability_of_surviving(alpha, beta, X):
    return special.expit(alpha + X @ beta)

## Question 5: Defining the loss
Our goal is to find the $\alpha$ and $\beta$ values that best match the observed data $(X, y)$. To do this, we will construct a loss function that, when given $\alpha$ and $\beta$, characterizes how good our predictions $\hat{y}$ are compared to the ground truth $y$. 

Mathematically, our loss function will be $$
    L(\alpha, \beta, X, y) = \text{sum}(\text{KL}(y, \hat{y})) + \frac{1}{2}\beta^T \beta,
$$ where:
- $\hat{y}$ is the vector of predicted probabilities (from Question 4), which is computed from $\alpha$, $\beta$, and $X$
- $\text{KL}(y, \hat{y})$ is the *Kullback-Liebler divergence*, which measures how different the ground truth $y$ is from the predicted probabilities $\hat{y}$
- $\text{sum}(\cdot)$ sums up the entries of a vector, in this case adding up the loss for each passenger in $X$
- $\frac{1}{2}\beta^T \beta$ is a *regularization term* that prevents overfitting.

Define a function `logistic_regression_loss(alpha_beta, X, y)` that computes $L(\alpha, \beta, X, y)$, where
- `alpha_beta` is a vector of length $1+ k$ that contains $\alpha$ in its first entry and $\beta$ in the remaining entries
- `X` is an $n$-by-$k$ matrix $X$, where each of the $n$ rows corresponds to an observation (a passenger), and each column corresponds to a feature
- `y` is a vector $y$ of length $n$, that is 1 if the passenger survived and 0 if they did not.

(Hint: check out SciPy's `special.kl_div`.) 

In [7]:
def logistic_regression_loss(alpha_beta, X, y):
    alpha = alpha_beta[0]
    beta = alpha_beta[1:]
    y_hat = probability_of_surviving(alpha, beta, X)
    return special.kl_div(y, y_hat).sum() + beta @ beta / 2

## Question 6: Logistic regression (the hard way)
Use SciPy's `optimize.minimize` to find the $\alpha$ and $\beta$ that best explain the data $(X,y)$. In other words, find $\alpha$ and $\beta$ that minimizes the function `logistic_regression_loss`. Use an initial guess of $\alpha = 0$, $\beta = 0$. Compare your result to the $\alpha$ and $\beta$ computed by scikit-learn, given by `model.intercept_` and `model.coef_`. (It will not match exactly but should be somewhat close.)

(Hint: you'll need to make use of the `args` argument for `optimize.minimize` to pass in `X` and `y`. Also, you may get a warning that the desired error was not achieved, but you can ignore this.)



In [8]:
import scipy.optimize as optimize
result = optimize.minimize(logistic_regression_loss,
                           np.zeros(1 + X.shape[1]),
                           args=(X, y))
result

      fun: 221.89164815464
 hess_inv: array([[ 4.50351878e-01, -1.51745711e-03,  7.81234120e-02,
         1.43831159e-01, -3.50948035e-03, -3.33709714e-01,
        -2.62166769e-01, -2.89718075e-01, -3.64965321e-01],
       [-1.51745711e-03,  8.56934904e-05,  5.59329891e-04,
         5.59083521e-04, -1.29795100e-05, -1.52338047e-03,
        -1.82518176e-03, -5.93194138e-04, -5.13364872e-04],
       [ 7.81234120e-02,  5.59329891e-04,  3.97790795e-02,
         3.39238036e-02, -9.52342900e-04, -9.13186383e-02,
        -8.43678170e-02, -6.87816883e-02, -8.74805851e-02],
       [ 1.43831159e-01,  5.59083521e-04,  3.39238036e-02,
         8.71606621e-02, -1.46318140e-03, -1.52059789e-01,
        -1.38064896e-01, -1.21079748e-01, -1.48863742e-01],
       [-3.50948035e-03, -1.29795100e-05, -9.52342900e-04,
        -1.46318140e-03,  5.11076399e-05,  2.90311781e-03,
         2.40182420e-03,  2.67019538e-03,  3.41368987e-03],
       [-3.33709714e-01, -1.52338047e-03, -9.13186383e-02,
        -1.52

In [9]:
result.x

array([ 0.12634051, -0.04302206, -0.36806953, -0.06156259,  0.00386969,
        2.32004758,  1.03282256, -0.13870222, -0.89412005])

In [10]:
model.intercept_[0], model.coef_[0]

# The numbers are comparable. Note that percent error isn't a great measure of closeness.
# More appropriate would be to compute the angle between the two vectors, by normalizing them,
# taking their dot product, and applying the arccosine function.

(0.10069429259465341,
 array([-0.04147541, -0.38556333, -0.09933112,  0.00329532,  2.63706203,
         1.12358593,  0.06128184, -1.08417348]))

## Question 7: Predictions

With what probability does the model learned in Question 6 think a 30-year-old male travelling alone who paid 50 pounds for his 2nd-class ticket will survive? What percentage of the passengers' outcomes does the model correctly predict, if we say that the model predicts survival if the probability of survival is greater than 0.5?

In [11]:
probability_of_surviving(result.x[0], result.x[1:], np.array([[30, 0, 0, 50, 0, 0, 1, 0]]))

# The model predicts a 24% chance of survival.

array([0.24795681])

In [12]:
(probability_of_surviving(result.x[0], result.x[1:], X).round() == y).mean()

# The accuracy is roughly 80%, the same as the scikit-learn model.

0.8060879368658399

# Submission instructions

Save this notebook (`CME193_Homework_2.ipynb`), and submit it on Canvas.